---
sidebar: sidebar 
permalink: install-setup/cluster-setup.html 
keywords: afx, afx system, cluster setup, setup 
summary: 'Después de que tu hardware de AFX haya sido instalado, puedes completar la configuración del clúster de ONTAP. Este proceso implica fases de configuración relacionadas que deberías realizar de forma secuencial. Como parte de esto, puedes añadir opcionalmente los nodos de computación de datos (DCN) que ejecutan el AI Data Engine (AIDE), lo que permite que el clúster de almacenamiento de AFX y el clúster de DCN funcionen como un solo sistema gestionado a través del mismo plano de control de ONTAP.' 
---
= Configure su clúster ONTAP del sistema de almacenamiento AFX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de que tu hardware de AFX haya sido instalado, puedes completar la configuración del clúster de ONTAP. Este proceso implica fases de configuración relacionadas que deberías realizar de forma secuencial. Como parte de esto, puedes añadir opcionalmente los nodos de computación de datos (DCN) que ejecutan el AI Data Engine (AIDE), lo que permite que el clúster de almacenamiento de AFX y el clúster de DCN funcionen como un solo sistema gestionado a través del mismo plano de control de ONTAP.



== Prepárate para configurar un sistema de almacenamiento AFX

Antes de configurar tu clúster ONTAP, deberías revisar los requisitos principales de AFX y las consideraciones adicionales de AIDE para asegurarte de que tienes toda la información y los recursos necesarios para completar el proceso de configuración con éxito.



=== Requisitos principales de AFX

Hay varios requisitos básicos que debes tener en cuenta al configurar tu clúster AFX.

.Instalación de hardware
Asegúrate de haber completado la instalación del hardware de tu sistema AFX. Para más información, consulta link:../install-setup/install-setup-workflow.html["Instale su sistema AFX"].

.Direccionamiento IP básico
Necesitas la siguiente configuración de dirección IP:

* Dirección IP de administración del clúster
+
La dirección IP de administración del clúster es una dirección IPv4 única para la interfaz de administración del clúster utilizada por el administrador del clúster para acceder a la SVM de administración y administrar el clúster.  Puede obtener esta dirección IP del administrador responsable de asignar direcciones IP en su organización.

* Máscara de subred de red
+
Durante la configuración del clúster, ONTAP requiere un conjunto de interfaces de red adecuadas para su configuración.  Puede ajustar la recomendación si es necesario.



.Configuración de red adicional
También necesitarás la siguiente información de red relacionada:

* Dirección IP de la puerta de enlace de red
* Nombres de dominio DNS
* Direcciones IP del servidor de nombres DNS
* Direcciones IP del servidor NTP
* Máscara de subred




=== Consideraciones adicionales de AIDE

Al instalar y configurar AFX por primera vez, puedes incluir opcionalmente NetApp AI Data Engine (AIDE). AIDE admite dos modelos de despliegue: AIDE software en servidores de terceros o nodos de computación de datos (DCNs) proporcionados por NetApp. Si planeas configurar AIDE, primero completa los prerrequisitos para tu modelo de despliegue:

* Para implantaciones de servidores de terceros, completa https://docs.netapp.com/us-en/ai-data-engine/install-aide-server/aide-mde-server-hardware-requirements.html["instalación de hardware para AI Data Engine en servidores de terceros"^], luego https://docs.netapp.com/us-en/ai-data-engine/install-setup/install-aide-as-software.html["instalar el software AIDE en servidores de terceros"^].
* Para las implantaciones de NetApp DCN, completa https://docs.netapp.com/us-en/ai-data-engine/install-dcn/aide-dcn-hardware-requirements.html["instalación de hardware para AI Data Engine en nodos de cómputo de datos proporcionados por NetApp"^].
* Obtén las direcciones y cualquier configuración de red relacionada para los nodos de cómputo.




== Realizar la configuración inicial del clúster

Puede conectar su dispositivo portátil al clúster AFX y establecer varios valores de configuración globales.

.Acerca de esta tarea
Hay cuatro áreas del clúster AFX que deben configurarse inicialmente.  Los primeros tres son obligatorios mientras que el último es opcional.

.Pasos
. Descubra su red de clústeres.
+
.. Conecte su computadora portátil al conmutador de administración y acceda a las computadoras y dispositivos de la red.
.. Abra el Explorador de archivos.
.. Seleccione *Red*; luego haga clic derecho y seleccione *Actualizar*.
.. Seleccione cualquiera de los íconos de ONTAP ; luego acepte cualquier certificado que aparezca en su pantalla.
+
Se muestra la interfaz de usuario del Administrador del sistema.



. Establecer la contraseña de administrador.
+
Proporcione y verifique la contraseña para el `admin` cuenta. Seleccione *Continuar*.

. Configura las direcciones IP para el clúster AFX y los nodos controladores.
+
Proporcione direcciones IP y máscaras de subred.

. Si estás instalando AI Data Engine con tu sistema de almacenamiento AFX, proporciona las direcciones IP de los tres nodos de cómputo.
. Configura los servicios de red, incluidos DNS y NIS. Selecciona *Continuar*.
+
Define los detalles de tus servidores DNS y NTP.

. Configurar el cifrado opcionalmente.
+
Puede definir los detalles para el cifrado del clúster. Seleccione *Continuar*.

+

NOTE: Para obtener información sobre cómo crear un clúster para un entorno que no sea Windows, consulte link:https://docs.netapp.com/us-en/ontap/software_setup/setup-cluster.html["Crear un clúster ONTAP y unir nodos"^].



.¿Qué sigue?
Serás redirigido a la página de inicio de sesión del Administrador del sistema.  Realice los pasos descritos en<<Configuración completa del clúster>> .



== Configuración completa del clúster

Una vez realizada la configuración inicial, puede completar la configuración del clúster ONTAP mediante el Administrador del sistema.

.Acerca de esta tarea
Hay tres áreas del clúster ONTAP del sistema AFX configuradas durante la instalación.  Complete los tres si es posible, pero sólo se requiere el primero.

.Antes de empezar
Necesitas tener la siguiente información:

* Detalles de configuración de VLAN.
* Detalles de configuración de NAS y/o S3.


.Pasos
. Sign in en el Administrador del sistema utilizando la cuenta de administrador que proporcionó durante la configuración inicial del clúster.  Observe la ventana emergente en la parte superior derecha con tres opciones de configuración.
. Seleccione *VLAN y etiquetado* y seleccione las opciones de red adecuadas para su entorno.
. Seleccione *Servicios de red* y configure los protocolos de acceso del cliente para el SVM de datos predeterminado.
. Seleccione *Contenedor de datos* y cree un volumen o un depósito S3.


.¿Qué sigue?
* Si incluiste AIDE como parte de la configuración del clúster AFX, completa los pasos adicionales de configuración de AIDE. La configuración de autenticación se aplica a todas las implementaciones de AIDE. Se requiere licencia para las implementaciones de NetApp DCN que usan funciones de AIDE con licencia; las implementaciones de servidores de terceros están enfocadas en los metadatos y no requieren una licencia de AIDE. Consulta https://docs.netapp.com/us-en/ai-data-engine/install-setup/cluster-setup-afx.html["Configura AI Data Engine"^] para más información.
* Deberíalink:../get-started/prepare-cluster-admin.html["Prepárese para administrar AFX"] antes de utilizar su clúster AFX en un entorno de producción.




== Información relacionada

* link:../get-started/learn-about-aide.html["Conoce el NetApp AI Data Engine"]
* link:../administer/configure-svm.html["Configurar un AFX SVM"]
* link:../get-started/prepare-cluster-admin.html["Prepárese para administrar AFX"]

