---
sidebar: sidebar 
permalink: install-setup/power-on-configure-switch.html 
keywords: afx, afx 1k, cable controllers, Cisco Nexus 9332D-GX2B, Cisco Nexus 9364D-GX2A, switches, switch, power on, configure switches, 
summary: Aprenda a encender y configurar los conmutadores para su sistema de almacenamiento AFX 1K. 
---
= Encienda y configure los conmutadores para su sistema de almacenamiento AFX 1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de cablear su sistema de almacenamiento AFX 1K, deberá encender y configurar los conmutadores Cisco Nexus 9332D-GX2B o 9364D-GX2A.

.Pasos
. Conecte los cables de alimentación de los interruptores a las fuentes de alimentación.
. Encienda cada interruptor.
. Configure los conmutadores para admitir el sistema de almacenamiento AFX 1K.
+
** Para los conmutadores Cisco Nexus 9332D-GX2B, consulte la documentación de los conmutadores de almacenamiento y clústerlink:https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-9332d-gx2b/configure-software-overview-9332d-cluster.html["Configurar el conmutador Cisco Nexus 9332D-GX2B"^] .
** Para los conmutadores Cisco Nexus 9364D-GX2A, consulte la documentación de los conmutadores de almacenamiento y clústerlink:https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-9364d-gx2a/configure-software-overview-9364d-cluster.html["Configurar el conmutador Cisco Nexus 9364D-GX2A"^] .




.¿Que sigue?
Después de configurar los conmutadores para su sistema de almacenamiento AFX 1K,link:power-on-hardware.html["Encienda el sistema de almacenamiento AFX 1K"] .
