---
settings:
  name: AFX
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos de AFX
    url: "/index.html"
  - section: release-notes
  - section: get-started
  - section: administer
  - section: svm-admin
  - title: Mantenimiento de hardware
    url: "/maintain-hardware.html"
  - section: rest
  - section: learn-more
  - title: Preguntas frecuentes
    url: "/faq-ontap-afx.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
