---
sidebar: sidebar 
permalink: install-afx-2k/install-network-reqs.html 
keywords: shared storage cluster switch 
summary: A partir de ONTAP 9.9.1, puede utilizar los conmutadores Cisco Nexus 9364d-gx2a para combinar la funcionalidad de almacenamiento y clúster en un escenario de conmutador compartido. 
---
= Requisitos de red para tu sistema de almacenamiento AFX 2K
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Anota la información necesaria para cada red a la que conectes tu sistema de almacenamiento AFX 2K.



== Recopilar información de la red

Antes de comenzar la instalación de tu sistema de almacenamiento AFX 2K, recopila la información de red necesaria

* Nombres de host y direcciones IP para cada uno de los controladores del sistema de almacenamiento y todos los conmutadores aplicables.
+
La mayoría de los controladores del sistema de almacenamiento se administran a través de la interfaz e0M conectándose al puerto de servicio Ethernet (ícono de llave inglesa).

+
Consulte la https://hwu.netapp.com["Hardware Universe"^] Para obtener la información más reciente.

* Dirección IP de administración del clúster
+
La dirección IP de administración del clúster es una dirección IP única para la interfaz de administración del clúster utilizada por el administrador del clúster para acceder a la máquina virtual de almacenamiento de administración y administrar el clúster.  Puede obtener esta dirección IP del administrador responsable de asignar direcciones IP en su organización.

* Máscara de subred de red
+
Durante la configuración del clúster, ONTAP recomienda un conjunto de interfaces de red adecuadas para su configuración.  Puede ajustar la recomendación si es necesario.

* Dirección IP de la puerta de enlace de red
* Direcciones IP de gestión de nodos (una por nodo)
* Nombres de dominio DNS
* Direcciones IP del servidor de nombres DNS
* Direcciones IP del servidor NTP
* Máscara de subred de datos
* Subred IP para la gestión del tráfico de red.




== Requisitos de red para conmutadores Cisco

Para la instalación y el mantenimiento de los switches Cisco Nexus 9808, Cisco Nexus 9332D-GX2 y 9364D-GX2A, asegúrate de revisar los requisitos de cableado y de red.



=== Requisitos de red

Necesita la siguiente información de red para todas las configuraciones del conmutador.

* Subred IP para la gestión del tráfico de red
* Nombres de host y direcciones IP para cada uno de los controladores del sistema de almacenamiento y todos los conmutadores aplicables
* Consulte la https://hwu.netapp.com["Hardware Universe"^] Para obtener la información más reciente.




=== Requisitos de cableado

* Tiene la cantidad y el tipo de cables y conectores de cables adecuados para sus conmutadores. Ver el https://hwu.netapp.com["Hardware Universe"^] .
* Dependiendo del tipo de conmutador que esté configurando inicialmente, deberá conectarse al puerto de consola del conmutador con el cable de consola incluido.


.¿Que sigue?
Después de revisar los requisitos de red, tú link:cable-hardware.html["Conecta los controladores y las estanterías de almacenamiento de tu sistema de almacenamiento AFX 2K"].
