---
sidebar: sidebar 
permalink: get-started/compare-unified-ontap.html 
keywords: afx, afx system, compare afx, compare unified ontap 
summary: 'Los sistemas AFX de NetApp ejecutan una personalidad personalizada de ONTAP que difiere de la personalidad de ONTAP (conocida como Unified ONTAP) que se ejecuta en el almacenamiento AFF y FAS .  Debe tener en cuenta cómo los sistemas AFX son similares y diferentes a los sistemas FAS y AFF .  Esto proporciona una perspectiva valiosa y puede ser útil al implementar AFX en su entorno.' 
---
= Compare el sistema de almacenamiento AFX con los sistemas AFF y FAS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los sistemas AFX de NetApp ejecutan una personalidad personalizada de ONTAP que difiere de la personalidad de ONTAP (conocida como Unified ONTAP) que se ejecuta en el almacenamiento AFF y FAS .  Debe tener en cuenta cómo los sistemas AFX son similares y diferentes a los sistemas FAS y AFF .  Esto proporciona una perspectiva valiosa y puede ser útil al implementar AFX en su entorno.


TIP: La documentación de AFX incluye enlaces a varios temas en el sitio de documentación de Unified ONTAP para obtener detalles sobre las características que se comportan de la misma manera independientemente de la personalidad de ONTAP .  El contenido adicional proporciona más profundidad que puede resultar útil al administrar su sistema de almacenamiento AFX.



== Diferencias de configuración

Hay algunas áreas en las que la configuración AFX difiere de los sistemas AFF y FAS .

Equilibrio de capacidad avanzado:: La función avanzada de equilibrio de capacidad, controlada mediante el `-gdd` El parámetro CLI está habilitado de forma predeterminada para todos los volúmenes FlexGroup .




== Capacidades de Unified ONTAP no admitidas o restringidas

NetApp AFX está optimizado para cargas de trabajo NAS y de objetos de alto rendimiento.  Debido a esto, existen diferencias con AFF y FAS , así como con los demás sistemas de almacenamiento Unified ONTAP .  Las siguientes características no están disponibles con NetApp AFX; la lista está organizada por característica principal o área funcional.  También debes revisar las actualizaciones y cambios de AFX enlink:../release-notes/whats-new-9171.html["Qué hay de nuevo"] basado en su lanzamiento.



=== Bloque y SAN

* Administración de SAN y acceso de clientes
* LUN y espacios de nombres NVMe
* Provisión gruesa de volúmenes




=== Agregados y almacenamiento físico

* MetroCluster
* Agregados físicos propiedad del nodo
* Gestión de RAID
* Cifrado agregado de NetApp (NAE)
* Desduplicación a nivel agregado
* SyncMirror (duplicación agregada)
* Nivelación de FabricPool




=== Replicación de datos (SnapMirror)


NOTE: Se admite la replicación de datos en ambas direcciones entre Unified ONTAP y AFX con las mismas restricciones de versiones descritas en https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html["Versiones de ONTAP compatibles para relaciones SnapMirror"^] (con algunas pequeñas excepciones).

* No se permite la replicación de un volumen desde un sistema AFF o FAS que contenga un espacio de nombres LUN o NVMe.
* Los volúmenes FlexGroup solo se pueden replicar desde AFX a Unified ONTAP versión 9.16.1 o posterior (debido a la necesidad de Advanced Capacity Balancing).




=== Manejabilidad

* API de ONTAPI (ZAPI)
* API REST para funciones no compatibles (como MetroCluster)
* Algunas limitaciones iniciales en las API REST para las estadísticas de rendimiento
* Soporte para AIQ Unified Manager
* Grafana Harvest versión 25.08.1 y posteriores
* NetApp Trident versión 25.10 y posteriores




== Cambios en la interfaz de la línea de comandos

La CLI de ONTAP disponible con AFX generalmente refleja la CLI disponible con los sistemas AFF y FAS .  Pero existen varias diferencias, entre ellas:

* Nuevos comandos AFX relacionados con:
+
** Visualización de la capacidad de la zona de disponibilidad de almacenamiento
** Medios de arranque


* No hay comandos relacionados con SAN
* Los comandos de gestión de agregados ya no son necesarios
* La visualización agregada ahora muestra toda la Zona de Disponibilidad de Almacenamiento (SAZ).




== Información relacionada

* link:../get-started/system-design.html["Características del sistema AFX"]
* link:../get-started/software-architecture.html["Detalles de la arquitectura AFX"]
* link:../faq-ontap-afx.html["Preguntas frecuentes sobre los sistemas de almacenamiento AFX"]
* link:../administer/additional-ontap-cluster.html["Administración adicional del clúster AFX"]
* link:../administer/additional-ontap-svm.html["Administración adicional de AFX SVM"]

