---
sidebar: sidebar 
permalink: get-started/ontap-afx-storage.html 
keywords: afx, afx system, learn, workloads, hardware, afx 1k, nx224, cisco 
summary: El sistema de almacenamiento AFX de NetApp se basa en una arquitectura de almacenamiento de próxima generación que evoluciona el modelo de almacenamiento ONTAP en una solución NAS desagregada de alto rendimiento.  AFX admite cargas de trabajo de archivos y objetos con tecnologías avanzadas y técnicas de procesamiento que proporcionan un rendimiento extremadamente alto. 
---
= Conozca los sistemas de almacenamiento AFX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El sistema de almacenamiento AFX de NetApp se basa en una arquitectura de almacenamiento de próxima generación que evoluciona el modelo de almacenamiento ONTAP en una solución NAS desagregada de alto rendimiento.  AFX admite cargas de trabajo de archivos y objetos con tecnologías avanzadas y técnicas de procesamiento que proporcionan un rendimiento extremadamente alto.



== Cargas de trabajo de aplicaciones típicas

El sistema de almacenamiento AFX de NetApp satisface las demandas únicas típicas de los entornos de IA/ML y otras aplicaciones centradas en datos relacionadas. El sistema de almacenamiento AFX es ideal para organizaciones que gestionan varias cargas de trabajo diferentes, entre ellas:

* Entrenamiento y refinamiento iterativo de modelos asociados con el aprendizaje profundo donde se requiere un ancho de banda alto y continuo y acceso a conjuntos de datos masivos.
* Procesamiento de diversos tipos de datos, incluidos texto, imágenes y vídeos.
* Aplicaciones de inferencia en tiempo real con baja latencia donde se necesitan ventanas de tiempo de respuesta estrictas.
* Procesos de aprendizaje automático y ciencia de datos que pueden beneficiarse de la gestión de datos de autoservicio por parte de ingenieros y científicos de datos.
* Cargas de trabajo que requieren alta concurrencia y E/S paralela, como sistemas multi-GPU con transporte RDMA.




== Características del diseño del sistema

El sistema AFX tiene varias características de diseño que le permiten funcionar como una plataforma NAS de alto rendimiento.

Desacoplar las capacidades de almacenamiento y computación:: A diferencia de los sistemas de almacenamiento AFF y FAS , los elementos de almacenamiento y cómputo AFX del clúster están desacoplados.  Los controladores AFX no están restringidos al acceso a un conjunto limitado de discos locales.
Eliminación de la gestión de agregados y RAID:: El administrador de almacenamiento ya no necesita administrar los agregados y los grupos RAID.  AFX se encarga de estas tareas, lo que simplifica la administración y ofrece una oportunidad para que los no especialistas administren sus datos.
Pool de almacenamiento único para el clúster:: Al desacoplar el procesamiento y el almacenamiento de AFX, junto con una gestión de almacenamiento simplificada, se obtiene un único grupo de almacenamiento.  Esta zona de disponibilidad de almacenamiento (SAZ) está disponible para todos los nodos del controlador en un clúster AFX. Verlink:../faq-ontap-afx.html["Preguntas frecuentes sobre los sistemas de almacenamiento AFX"] Para más detalles.
Rendimiento alto:: AFX está diseñado para el alto rendimiento que necesitan las aplicaciones especializadas de IA/ML.  Puede hacer un uso más eficiente del hardware moderno para proporcionar un ancho de banda alto y sostenido con una latencia ultrabaja.
Simplicidad operativa:: El grupo de almacenamiento único, junto con otras características que incluyen la gestión automática del almacenamiento, proporciona un modelo administrativo y operativo mucho más simple.
Escalabilidad:: El conjunto de nodos de controlador y estantes de almacenamiento en un clúster se puede ampliar de forma independiente según las necesidades de la aplicación.  Existen requisitos de administración limitados e interrupciones al agregar controladores o estantes.
Movilidad de datos mejorada:: Los volúmenes se pueden mover entre los nodos del controlador del clúster sin generar interrupciones y sin necesidad de copiar datos.  En su lugar se actualizan los directorios de metadatos y los punteros de índice.  Esto mejora drásticamente el rendimiento durante los procedimientos administrativos típicos, así como la recuperación en escenarios de falla.




== Infraestructura de hardware

El sistema de almacenamiento NetApp AFX ofrece una solución unificada de hardware y software que crea una experiencia simplificada específica para las necesidades de los clientes de NAS de alto rendimiento.

Los siguientes componentes de hardware se utilizan con clústeres AFX:

* Controladores AFX 1K
* Estantes NX224
* Conmutadores Cisco Nexus 9332D-GX2B o Nexus 9364D-GX2A




== Información relacionada

* https://www.netapp.com/afx/["AFX de NetApp"^]

