---
sidebar: sidebar 
permalink: get-started/ontap-afx-storage.html 
keywords: afx, afx system, learn, workloads, hardware, afx 1k, nx224, cisco 
summary: El sistema de almacenamiento AFX de NetApp se basa en una arquitectura de almacenamiento de próxima generación que evoluciona el modelo de almacenamiento ONTAP en una solución NAS desagregada de alto rendimiento.  AFX admite cargas de trabajo de archivos y objetos con tecnologías avanzadas y técnicas de procesamiento que proporcionan un rendimiento extremadamente alto. 
---
= Conozca los sistemas de almacenamiento AFX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El sistema de almacenamiento AFX de NetApp se basa en una arquitectura de almacenamiento de próxima generación que evoluciona el modelo de almacenamiento ONTAP en una solución NAS desagregada de alto rendimiento.  AFX admite cargas de trabajo de archivos y objetos con tecnologías avanzadas y técnicas de procesamiento que proporcionan un rendimiento extremadamente alto.



== Cargas de trabajo de aplicaciones típicas

El sistema de almacenamiento NetApp AFX satisface las demandas únicas de las cargas de trabajo de objetos NAS y S3 que requieren alto rendimiento y escalabilidad independiente.  Estas aplicaciones se benefician de un diseño avanzado basado en alta concurrencia y E/S paralelas.  AFX es ideal para organizaciones que implementan y administran varios tipos diferentes de cargas de trabajo de aplicaciones, incluyendo:

* Entrenamiento y refinamiento iterativo de modelos asociados con el aprendizaje profundo donde se requiere un ancho de banda alto y continuo y acceso a conjuntos de datos masivos.
* Procesamiento de diversos tipos de datos, incluidos texto, imágenes y vídeos.
* Aplicaciones de inferencia en tiempo real con baja latencia donde se necesitan ventanas de tiempo de respuesta estrictas.
* Procesos de aprendizaje automático y ciencia de datos que pueden beneficiarse de la gestión de datos de autoservicio por parte de ingenieros y científicos de datos.




== Características del diseño del sistema

El sistema AFX tiene varias características de diseño que le permiten funcionar como una plataforma NAS de alto rendimiento.

Desacoplar las capacidades de almacenamiento y computación:: A diferencia de otros sistemas de almacenamiento NetApp ONTAP , los elementos de computación y almacenamiento de un clúster AFX están desacoplados y unidos a través de una red conmutada.  La propiedad del disco ya no está ligada a nodos específicos, lo que proporciona varias ventajas.  Por ejemplo, los componentes de computación y almacenamiento de un clúster AFX se pueden ampliar de forma independiente.
Gestión automatizada del almacenamiento:: Los agregados físicos ya no están disponibles para el administrador de almacenamiento de AFX.  En cambio, AFX gestiona automáticamente las asignaciones de capacidad virtual para los nodos, así como la configuración del grupo RAID, cuando se agregan nuevos estantes de almacenamiento al clúster.  Este diseño simplifica la administración y ofrece la oportunidad a los no especialistas de gestionar sus datos.
Pool de almacenamiento único para el clúster:: Debido a que los nodos y estantes de almacenamiento están desacoplados con NetApp AFX, toda la capacidad de almacenamiento del clúster se reúne en un único grupo conocido como Zona de Disponibilidad de Almacenamiento (SAZ).  Los discos y estantes de una SAZ están disponibles para todos los nodos de almacenamiento de un clúster AFX para operaciones de lectura y escritura.  Además, todos los nodos del clúster pueden participar en la reconstrucción de discos en caso de fallo. Referirse alink:../faq-ontap-afx.html["Preguntas frecuentes sobre los sistemas de almacenamiento AFX"] Para más detalles.
Rendimiento alto:: NetApp AFX proporciona un ancho de banda elevado y sostenido con una latencia ultrabaja, por lo que está diseñado para cargas de trabajo NAS y de objetos de alto rendimiento.  AFX utiliza el hardware moderno más reciente, así como estantes de almacenamiento capaces de manejar una alta proporción de nodos por disco gracias a su arquitectura única.  Ampliar la escala de los nodos de almacenamiento más allá de la relación típica 1:1 (nodo:estante) maximiza el perfil de rendimiento posible de los discos hasta sus límites máximos.  Este diseño proporciona eficiencia y densidad de almacenamiento para sus aplicaciones más críticas.
escala independiente y masiva:: Gracias a sus nodos y estantes de almacenamiento desacoplados, un clúster AFX puede ampliarse de forma independiente y sin interrupciones según las necesidades de su aplicación.  Puede agregar nodos de almacenamiento para obtener más CPU y rendimiento, o agregar estantes para obtener más capacidad de almacenamiento y rendimiento de disco.  La arquitectura NetApp AFX ofrece nuevas posibilidades para el tamaño máximo de su clúster.  Para conocer los límites más recientes del clúster AFX según su versión de ONTAP , consulte el NetApp Hardware Universe.
movilidad de datos sin copia:: Los clientes NAS y de objetos acceden a volúmenes en el clúster ONTAP .  Puede reubicar volúmenes entre los nodos sin interrupciones para lograr sus objetivos de equilibrio de capacidad y rendimiento.  Con Unified ONTAP, el movimiento de volumen se realiza utilizando la tecnología SnapMirror , lo que puede requerir tiempo y capacidad temporal adicional.  Pero con AFX, ya no es necesaria una operación de copia de datos dentro de la Zona de Disponibilidad de Almacenamiento (SAZ) compartida.  En cambio, solo se mueven los metadatos del volumen, lo que mejora drásticamente el rendimiento. Referirse alink:../faq-ontap-afx.html["Preguntas frecuentes sobre los sistemas de almacenamiento AFX"] Para más detalles.
Funcionalidad HA mejorada:: NetApp AFX ofrece una serie de mejoras para la configuración y el procesamiento de alta disponibilidad (HA).  AFX elimina la necesidad de conectar directamente los nodos asociados de alta disponibilidad y, en su lugar, permite que los pares de alta disponibilidad se comuniquen a través de la red interna del clúster.  Este diseño ofrece a los administradores la opción de implementar pares HA en racks o filas separadas en un centro de datos para una mayor tolerancia a fallos.  Además, la movilidad de copia cero de AFX se extiende a escenarios de conmutación por error de alta disponibilidad.  Cuando falla un nodo, sus volúmenes se transferirán al socio HA para confirmar las escrituras restantes en el disco.  Luego, ONTAP equilibra los volúmenes de manera uniforme entre todos los nodos supervivientes del clúster.  Esto significa que ya no es necesario tener en cuenta el rendimiento de la conmutación por error del almacenamiento en el diseño inicial de la ubicación de sus datos.




== Infraestructura de hardware

El sistema de almacenamiento NetApp AFX ofrece una solución unificada de hardware y software que crea una experiencia simplificada específica para las necesidades de los clientes de NAS de alto rendimiento.


TIP: Deberías revisar ellink:../faq-ontap-afx.html["Preguntas frecuentes sobre los sistemas de almacenamiento AFX"] Para obtener más información sobre la interoperabilidad del hardware y las opciones de actualización.

Los siguientes componentes de hardware se utilizan con clústeres AFX:

* Controladores AFX 1K
* Estantes NX224
* Conmutadores Cisco Nexus 9332D-GX2B o Nexus 9364D-GX2A




== Información relacionada

* https://hwu.netapp.com/["NetApp Hardware Universe"^]
* https://www.netapp.com/afx/["AFX de NetApp"^]

