---
sidebar: sidebar 
permalink: get-started/system-design.html 
keywords: afx, afx system, characteristics, design 
summary: El sistema de almacenamiento NetApp AFX tiene varias características que le permiten funcionar como una plataforma NAS de alto rendimiento. 
---
= Características del sistema de almacenamiento AFX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El sistema de almacenamiento NetApp AFX tiene varias características que le permiten funcionar como una plataforma NAS de alto rendimiento.

Desacoplar las capacidades de almacenamiento y computación:: A diferencia de los sistemas de almacenamiento AFF y FAS , los elementos de almacenamiento y cómputo AFX del clúster están desacoplados.  Los controladores AFX no están restringidos al acceso a un conjunto limitado de discos locales.
Eliminación de la gestión de agregados y RAID:: El administrador de almacenamiento ya no necesita administrar los agregados y los grupos RAID.  AFX se encarga de estas tareas, lo que simplifica la administración y ofrece una oportunidad para que los no especialistas administren sus datos.
Pool de almacenamiento único para el clúster:: Al desacoplar el procesamiento y el almacenamiento de AFX, junto con una gestión de almacenamiento simplificada, se obtiene un único grupo de almacenamiento.  Esta zona de disponibilidad de almacenamiento (SAZ) está disponible para todos los nodos del controlador en un clúster AFX. Verlink:../faq-ontap-afx.html["Preguntas frecuentes sobre los sistemas de almacenamiento AFX"] Para más detalles.
Rendimiento alto:: AFX está diseñado para el alto rendimiento que necesitan las aplicaciones especializadas de IA/ML.  Puede hacer un uso más eficiente del hardware moderno para proporcionar un ancho de banda alto y sostenido con una latencia ultrabaja.
Simplicidad operativa:: El grupo de almacenamiento único, junto con otras características que incluyen la gestión automática del almacenamiento, proporciona un modelo administrativo y operativo mucho más simple.
Escalabilidad:: El conjunto de nodos de controlador y estantes de almacenamiento en un clúster se puede ampliar de forma independiente según las necesidades de la aplicación.  Existen requisitos de administración limitados e interrupciones al agregar controladores o estantes.
Movilidad de datos mejorada:: Los volúmenes se pueden mover entre los nodos del controlador del clúster sin generar interrupciones y sin necesidad de copiar datos.  En su lugar se actualizan los directorios de metadatos y los punteros de índice.  Esto mejora drásticamente el rendimiento durante los procedimientos administrativos típicos, así como la recuperación en escenarios de falla.

