---
sidebar: sidebar 
permalink: release-notes/whats-new-9181.html 
keywords: 'afx, release notes, what"s new, 9.18.1' 
summary: Conozca las nuevas capacidades incluidas con ONTAP 9.18.1 que están disponibles con su sistema de almacenamiento AFX. 
---
= Novedades de ONTAP 9.18.1 para sistemas de almacenamiento AFX
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Conozca las nuevas capacidades incluidas con ONTAP 9.18.1 que están disponibles con su sistema de almacenamiento AFX.


NOTE: Hay varias funciones nuevas disponibles para AFX con ONTAP 9.18.1. Algunas de ellas son específicas de AFX mientras que muchas otras se derivan de una base de producto común compartida. Además de revisar las funciones de AFX que se describen a continuación, también deberías consultar https://docs.netapp.com/us-en/ontap/release-notes/whats-new-9181.html["Novedades de ONTAP 9.18.1"^].



[[storage-resource-management-enhancements]]
== Mejoras en la gestión de recursos de almacenamiento

[cols="2,4"]
|===
| Actualizar | Descripción 


| Colocación de volumen mejorada  a| 
NetApp AFX equilibra automáticamente la ubicación de los volúmenes en todos los nodos de un clúster.  En versiones anteriores de ONTAP , el algoritmo de ubicación se basaba en el número de volúmenes del clúster.  A cada nodo se le asigna el mismo número de volúmenes independientemente de su actividad.  A partir de ONTAP 9.18.1, el algoritmo se ha mejorado para tener en cuenta el rendimiento de los nodos al colocar o mover volúmenes.  Esto da como resultado un mejor equilibrio del rendimiento entre los nodos del clúster AFX y hace mucho menos probable que un solo nodo se sobrecargue.

|===
.Información relacionada
* https://docs.netapp.com/us-en/ontap/release-notes/index.html["Aspectos destacados del lanzamiento de ONTAP 9"^]

